//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tekinroads.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPermission
    {
        public byte PersonPermissionId { get; set; }
        public Nullable<byte> PersonId { get; set; }
        public Nullable<byte> PermissionId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
