//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekinroadsPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonPermissions = new HashSet<PersonPermission>();
        }
    
        public byte PersonId { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
    
        public virtual ICollection<PersonPermission> PersonPermissions { get; set; }
    }
}
